### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by Mte90** [stuartlangridge/hushboard#19]
As it is in python a pip package will be handy and will let to install it in a lot of distro.

**Comment by stuartlangridge** [comment]
I'm afraid not; Hushboard is an end-user application, and `pip` is in my opinion not for distributing end-user applications. A user should not have to know what `pip` is, and should not have to use it to install anything; `pip` is a developer tool. So there won't be a Hushboard pypi package from me, sorry.

**Comment by Mte90** [comment]
This is true but looking at the code there is just the launcher.
There are packages like Spyder that is a graphical ide that is available on pip as example but I understand your point.
I will see to download it from git and run on my system without pip.
