### ISSUE TITLE
__main__.py hover tool tip

### ISSUE THREAD

**Issue by ralight** [stuartlangridge/hushboard#9]
Running on kubuntu 20.04, if I mouse over the sys tray icon I get a nice popup with `__main__.py`, which doesn't seem friendly.

Here's a pic:
![hb02](https://user-images.githubusercontent.com/79578/104049754-6049be80-51dd-11eb-8736-20553b94b145.png)

Unrelated, but I quite like that the sys tray icon has been caught in transition by the screenshot tool due to the delay between me pressing PrtScr and the screenshot being taken.

**Comment by jbouter** [comment]
Once #8 has been merged and @popey rebuilds the snap using the `setup.py`, this will be fixed.

**Comment by jbouter** [comment]
Example:

![Screenshot_20210108_202750](https://user-images.githubusercontent.com/6340770/104056028-13231800-51f0-11eb-8547-1033956f51da.png)
